NAME: IA_generated_3
COMMENT: Instancia_generada_por_IA_menor_escala
TYPE: TSPDC
DIMENSION: 5
CAPACITY: 31
EDGE_WEIGHT_TYPE: EXPLICIT
EDGE_WEIGHT_FORMAT: FULL_MATRIX
EDGE_WEIGHT_SECTION:
  10000000        40        49        74
        40  10000000        68        35
        49        68  10000000       100
        74        35       100  10000000
 DEMAND_SECTION:
 0   31   0
 1   13   6
 2   7   14
 3   11   4
 4   0   24
