import { SolutionData } from "../types/tsppd";

export const DEFAULT_SOLUTIONS: Record<string, SolutionData> = {
  "Solucion_5_Clientes_ID10_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID10_H_01",
    "numCustomers": 5,
    "instanceId": 10,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 30,
    "objectiveValue": 188.7,
    "totalDistance": 187,
    "handlingCost": 1.7,
    "tour": [
      0,
      2,
      5,
      4,
      1,
      3,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 30,
        "beta": 12,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 5,
        "beta": 1,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 9,
        "beta": 5,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 4,
        "beta": 4,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 1,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 11,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 2,
        "distance": 49,
        "deliverA": 9,
        "pickupB": 5,
        "aOnTruck": 30,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 9,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 2:</strong> El camión viaja una distancia de 49 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>9 unidades α</span> (entrega requerida). ⚠️ Se requirieron 9 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>5 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 2,
        "to": 5,
        "distance": 28,
        "deliverA": 11,
        "pickupB": 0,
        "aOnTruck": 21,
        "bOnTruck": 5,
        "slots": [
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 21,
        "handlingCost": 0.6,
        "explanation": "<strong>Paso 2 — Cliente 2 → Cliente 5:</strong> Recorrido de 28 km. Se entregan <span style='color:#ef4444;font-weight:600;'>11 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 21 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (21 operaciones × h=0.1 = 0.60 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 5,
        "to": 4,
        "distance": 8,
        "deliverA": 1,
        "pickupB": 2,
        "aOnTruck": 10,
        "bOnTruck": 5,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 6,
        "handlingCost": 0,
        "explanation": "<strong>Paso 3 — Cliente 5 → Cliente 4:</strong> Recorrido de 8 km. Se entregan <span style='color:#ef4444;font-weight:600;'>1 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 6 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (6 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 4,
        "to": 1,
        "distance": 50,
        "deliverA": 5,
        "pickupB": 1,
        "aOnTruck": 9,
        "bOnTruck": 7,
        "slots": [
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 30,
        "handlingCost": 1.1,
        "explanation": "<strong>Paso 4 — Cliente 4 → Cliente 1:</strong> Recorrido de 50 km. Se entregan <span style='color:#ef4444;font-weight:600;'>5 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 30 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (30 operaciones × h=0.1 = 1.10 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>1 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 1,
        "to": 3,
        "distance": 18,
        "deliverA": 4,
        "pickupB": 4,
        "aOnTruck": 4,
        "bOnTruck": 8,
        "slots": [
          "A",
          "A",
          "EMPTY",
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 21,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 1 → Cliente 3:</strong> Recorrido de 18 km. Se entregan <span style='color:#ef4444;font-weight:600;'>4 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 21 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (21 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>4 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 3,
        "to": 0,
        "distance": 34,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 12,
        "slots": [
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 3 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 34 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>12 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        50,
        49,
        34,
        76,
        74
      ],
      [
        50,
        10000000,
        29,
        18,
        50,
        54
      ],
      [
        49,
        29,
        10000000,
        22,
        27,
        28
      ],
      [
        34,
        18,
        22,
        10000000,
        49,
        50
      ],
      [
        76,
        50,
        27,
        49,
        10000000,
        8
      ],
      [
        74,
        54,
        28,
        50,
        8,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID1_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID1_H_01",
    "numCustomers": 5,
    "instanceId": 1,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 32,
    "objectiveValue": 296.5,
    "totalDistance": 295,
    "handlingCost": 1.5,
    "tour": [
      0,
      2,
      1,
      5,
      3,
      4,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 32,
        "beta": 16,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 15,
        "beta": 3,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 4,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 3,
        "beta": 3,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 3,
        "beta": 8,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 7,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 2,
        "distance": 35,
        "deliverA": 4,
        "pickupB": 2,
        "aOnTruck": 32,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 4,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 2:</strong> El camión viaja una distancia de 35 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>4 unidades α</span> (entrega requerida). ⚠️ Se requirieron 4 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 2,
        "to": 1,
        "distance": 33,
        "deliverA": 15,
        "pickupB": 3,
        "aOnTruck": 28,
        "bOnTruck": 2,
        "slots": [
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 19,
        "handlingCost": 0.2,
        "explanation": "<strong>Paso 2 — Cliente 2 → Cliente 1:</strong> Recorrido de 33 km. Se entregan <span style='color:#ef4444;font-weight:600;'>15 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 19 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (19 operaciones × h=0.1 = 0.20 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>3 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 1,
        "to": 5,
        "distance": 44,
        "deliverA": 7,
        "pickupB": 0,
        "aOnTruck": 13,
        "bOnTruck": 5,
        "slots": [
          "B",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 26,
        "handlingCost": 0.5,
        "explanation": "<strong>Paso 3 — Cliente 1 → Cliente 5:</strong> Recorrido de 44 km. Se entregan <span style='color:#ef4444;font-weight:600;'>7 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 26 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (26 operaciones × h=0.1 = 0.50 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 5,
        "to": 3,
        "distance": 100,
        "deliverA": 3,
        "pickupB": 3,
        "aOnTruck": 6,
        "bOnTruck": 5,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 32,
        "handlingCost": 0.8,
        "explanation": "<strong>Paso 4 — Cliente 5 → Cliente 3:</strong> Recorrido de 100 km. Se entregan <span style='color:#ef4444;font-weight:600;'>3 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 32 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (32 operaciones × h=0.1 = 0.80 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>3 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 3,
        "to": 4,
        "distance": 52,
        "deliverA": 3,
        "pickupB": 8,
        "aOnTruck": 3,
        "bOnTruck": 8,
        "slots": [
          "A",
          "EMPTY",
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY"
        ],
        "handlingCount": 13,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 3 → Cliente 4:</strong> Recorrido de 52 km. Se entregan <span style='color:#ef4444;font-weight:600;'>3 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 13 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (13 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>8 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 4,
        "to": 0,
        "distance": 31,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 16,
        "slots": [
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 4 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 31 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>16 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        67,
        35,
        83,
        31,
        91
      ],
      [
        67,
        10000000,
        33,
        114,
        81,
        44
      ],
      [
        35,
        33,
        10000000,
        90,
        50,
        59
      ],
      [
        83,
        114,
        90,
        10000000,
        52,
        100
      ],
      [
        31,
        81,
        50,
        52,
        10000000,
        89
      ],
      [
        91,
        44,
        59,
        100,
        89,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID2_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID2_H_01",
    "numCustomers": 5,
    "instanceId": 2,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 28,
    "objectiveValue": 261.5,
    "totalDistance": 260,
    "handlingCost": 1.5,
    "tour": [
      0,
      5,
      2,
      1,
      3,
      4,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 28,
        "beta": 26,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 8,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 11,
        "beta": 7,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 2,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 4,
        "beta": 15,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 3,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 5,
        "distance": 16,
        "deliverA": 3,
        "pickupB": 0,
        "aOnTruck": 28,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 3,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 5:</strong> El camión viaja una distancia de 16 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>3 unidades α</span> (entrega requerida). ⚠️ Se requirieron 3 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 5,
        "to": 2,
        "distance": 47,
        "deliverA": 11,
        "pickupB": 7,
        "aOnTruck": 25,
        "bOnTruck": 0,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 14,
        "handlingCost": 0,
        "explanation": "<strong>Paso 2 — Cliente 5 → Cliente 2:</strong> Recorrido de 47 km. Se entregan <span style='color:#ef4444;font-weight:600;'>11 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 14 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (14 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>7 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 2,
        "to": 1,
        "distance": 42,
        "deliverA": 8,
        "pickupB": 2,
        "aOnTruck": 14,
        "bOnTruck": 7,
        "slots": [
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 28,
        "handlingCost": 1.3,
        "explanation": "<strong>Paso 3 — Cliente 2 → Cliente 1:</strong> Recorrido de 42 km. Se entregan <span style='color:#ef4444;font-weight:600;'>8 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 28 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (28 operaciones × h=0.1 = 1.30 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 1,
        "to": 3,
        "distance": 23,
        "deliverA": 2,
        "pickupB": 2,
        "aOnTruck": 6,
        "bOnTruck": 9,
        "slots": [
          "EMPTY",
          "EMPTY",
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "EMPTY",
          "A",
          "EMPTY",
          "A",
          "A",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 13,
        "handlingCost": 0,
        "explanation": "<strong>Paso 4 — Cliente 1 → Cliente 3:</strong> Recorrido de 23 km. Se entregan <span style='color:#ef4444;font-weight:600;'>2 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 13 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (13 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 3,
        "to": 4,
        "distance": 84,
        "deliverA": 4,
        "pickupB": 15,
        "aOnTruck": 4,
        "bOnTruck": 11,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "A",
          "EMPTY",
          "A",
          "EMPTY",
          "A",
          "A",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 19,
        "handlingCost": 0.2,
        "explanation": "<strong>Paso 5 — Cliente 3 → Cliente 4:</strong> Recorrido de 84 km. Se entregan <span style='color:#ef4444;font-weight:600;'>4 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 19 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (19 operaciones × h=0.1 = 0.20 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>15 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 4,
        "to": 0,
        "distance": 48,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 26,
        "slots": [
          "B",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 4 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 48 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>26 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        76,
        38,
        67,
        48,
        16
      ],
      [
        76,
        10000000,
        42,
        23,
        102,
        88
      ],
      [
        38,
        42,
        10000000,
        44,
        78,
        47
      ],
      [
        67,
        23,
        44,
        10000000,
        84,
        82
      ],
      [
        48,
        102,
        78,
        84,
        10000000,
        57
      ],
      [
        16,
        88,
        47,
        82,
        57,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID3_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID3_H_01",
    "numCustomers": 5,
    "instanceId": 3,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 30,
    "objectiveValue": 279.8,
    "totalDistance": 279,
    "handlingCost": 0.8,
    "tour": [
      0,
      5,
      2,
      3,
      4,
      1,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 30,
        "beta": 10,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 2,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 6,
        "beta": 4,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 1,
        "beta": 1,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 2,
        "beta": 5,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 19,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 5,
        "distance": 69,
        "deliverA": 19,
        "pickupB": 0,
        "aOnTruck": 30,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 19,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 5:</strong> El camión viaja una distancia de 69 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>19 unidades α</span> (entrega requerida). ⚠️ Se requirieron 19 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 5,
        "to": 2,
        "distance": 39,
        "deliverA": 6,
        "pickupB": 4,
        "aOnTruck": 11,
        "bOnTruck": 0,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 26,
        "handlingCost": 0.1,
        "explanation": "<strong>Paso 2 — Cliente 5 → Cliente 2:</strong> Recorrido de 39 km. Se entregan <span style='color:#ef4444;font-weight:600;'>6 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 26 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (26 operaciones × h=0.1 = 0.10 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>4 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 2,
        "to": 3,
        "distance": 24,
        "deliverA": 1,
        "pickupB": 1,
        "aOnTruck": 5,
        "bOnTruck": 4,
        "slots": [
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 5,
        "handlingCost": 0,
        "explanation": "<strong>Paso 3 — Cliente 2 → Cliente 3:</strong> Recorrido de 24 km. Se entregan <span style='color:#ef4444;font-weight:600;'>1 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 5 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (5 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>1 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 3,
        "to": 4,
        "distance": 71,
        "deliverA": 2,
        "pickupB": 5,
        "aOnTruck": 4,
        "bOnTruck": 5,
        "slots": [
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 30,
        "handlingCost": 0.7,
        "explanation": "<strong>Paso 4 — Cliente 3 → Cliente 4:</strong> Recorrido de 71 km. Se entregan <span style='color:#ef4444;font-weight:600;'>2 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 30 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (30 operaciones × h=0.1 = 0.70 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>5 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 4,
        "to": 1,
        "distance": 53,
        "deliverA": 2,
        "pickupB": 0,
        "aOnTruck": 2,
        "bOnTruck": 10,
        "slots": [
          "EMPTY",
          "A",
          "A",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY"
        ],
        "handlingCount": 3,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 4 → Cliente 1:</strong> Recorrido de 53 km. Se entregan <span style='color:#ef4444;font-weight:600;'>2 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 3 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (3 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 1,
        "to": 0,
        "distance": 23,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 10,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 1 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 23 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>10 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        23,
        87,
        66,
        73,
        69
      ],
      [
        23,
        10000000,
        72,
        49,
        53,
        65
      ],
      [
        87,
        72,
        10000000,
        24,
        91,
        39
      ],
      [
        66,
        49,
        24,
        10000000,
        71,
        39
      ],
      [
        73,
        53,
        91,
        71,
        10000000,
        105
      ],
      [
        69,
        65,
        39,
        39,
        105,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID4_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID4_H_01",
    "numCustomers": 5,
    "instanceId": 4,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 33,
    "objectiveValue": 252.7,
    "totalDistance": 252,
    "handlingCost": 0.7,
    "tour": [
      0,
      1,
      5,
      2,
      4,
      3,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 33,
        "beta": 14,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 12,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 2,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 1,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 3,
        "beta": 12,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 15,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 1,
        "distance": 41,
        "deliverA": 12,
        "pickupB": 2,
        "aOnTruck": 33,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 12,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 1:</strong> El camión viaja una distancia de 41 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>12 unidades α</span> (entrega requerida). ⚠️ Se requirieron 12 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 1,
        "to": 5,
        "distance": 45,
        "deliverA": 15,
        "pickupB": 0,
        "aOnTruck": 21,
        "bOnTruck": 2,
        "slots": [
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 27,
        "handlingCost": 0.2,
        "explanation": "<strong>Paso 2 — Cliente 1 → Cliente 5:</strong> Recorrido de 45 km. Se entregan <span style='color:#ef4444;font-weight:600;'>15 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 27 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (27 operaciones × h=0.1 = 0.20 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 5,
        "to": 2,
        "distance": 58,
        "deliverA": 2,
        "pickupB": 0,
        "aOnTruck": 6,
        "bOnTruck": 2,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 29,
        "handlingCost": 0.2,
        "explanation": "<strong>Paso 3 — Cliente 5 → Cliente 2:</strong> Recorrido de 58 km. Se entregan <span style='color:#ef4444;font-weight:600;'>2 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 29 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (29 operaciones × h=0.1 = 0.20 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 2,
        "to": 4,
        "distance": 59,
        "deliverA": 3,
        "pickupB": 12,
        "aOnTruck": 4,
        "bOnTruck": 2,
        "slots": [
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 33,
        "handlingCost": 0.3,
        "explanation": "<strong>Paso 4 — Cliente 2 → Cliente 4:</strong> Recorrido de 59 km. Se entregan <span style='color:#ef4444;font-weight:600;'>3 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 33 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (33 operaciones × h=0.1 = 0.30 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>12 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 4,
        "to": 3,
        "distance": 22,
        "deliverA": 1,
        "pickupB": 0,
        "aOnTruck": 1,
        "bOnTruck": 14,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY"
        ],
        "handlingCount": 5,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 4 → Cliente 3:</strong> Recorrido de 22 km. Se entregan <span style='color:#ef4444;font-weight:600;'>1 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 5 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (5 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 3,
        "to": 0,
        "distance": 27,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 14,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 3 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 27 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>14 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        41,
        101,
        27,
        49,
        44
      ],
      [
        41,
        10000000,
        94,
        47,
        65,
        45
      ],
      [
        101,
        94,
        10000000,
        76,
        59,
        58
      ],
      [
        27,
        47,
        76,
        10000000,
        22,
        21
      ],
      [
        49,
        65,
        59,
        22,
        10000000,
        23
      ],
      [
        44,
        45,
        58,
        21,
        23,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID5_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID5_H_01",
    "numCustomers": 5,
    "instanceId": 5,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 34,
    "objectiveValue": 197.3,
    "totalDistance": 196,
    "handlingCost": 1.3,
    "tour": [
      0,
      5,
      1,
      4,
      3,
      2,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 34,
        "beta": 18,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 5,
        "beta": 1,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 9,
        "beta": 5,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 8,
        "beta": 10,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 1,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 11,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 5,
        "distance": 59,
        "deliverA": 11,
        "pickupB": 0,
        "aOnTruck": 34,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 11,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 5:</strong> El camión viaja una distancia de 59 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>11 unidades α</span> (entrega requerida). ⚠️ Se requirieron 11 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 5,
        "to": 1,
        "distance": 27,
        "deliverA": 5,
        "pickupB": 1,
        "aOnTruck": 23,
        "bOnTruck": 0,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 16,
        "handlingCost": 0,
        "explanation": "<strong>Paso 2 — Cliente 5 → Cliente 1:</strong> Recorrido de 27 km. Se entregan <span style='color:#ef4444;font-weight:600;'>5 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 16 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (16 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>1 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 1,
        "to": 4,
        "distance": 31,
        "deliverA": 1,
        "pickupB": 2,
        "aOnTruck": 18,
        "bOnTruck": 1,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 17,
        "handlingCost": 0.1,
        "explanation": "<strong>Paso 3 — Cliente 1 → Cliente 4:</strong> Recorrido de 31 km. Se entregan <span style='color:#ef4444;font-weight:600;'>1 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 17 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (17 operaciones × h=0.1 = 0.10 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 4,
        "to": 3,
        "distance": 25,
        "deliverA": 8,
        "pickupB": 10,
        "aOnTruck": 17,
        "bOnTruck": 3,
        "slots": [
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 34,
        "handlingCost": 1.2,
        "explanation": "<strong>Paso 4 — Cliente 4 → Cliente 3:</strong> Recorrido de 25 km. Se entregan <span style='color:#ef4444;font-weight:600;'>8 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 34 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (34 operaciones × h=0.1 = 1.20 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>10 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 3,
        "to": 2,
        "distance": 14,
        "deliverA": 9,
        "pickupB": 5,
        "aOnTruck": 9,
        "bOnTruck": 13,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "EMPTY",
          "A",
          "A",
          "A",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 21,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 3 → Cliente 2:</strong> Recorrido de 14 km. Se entregan <span style='color:#ef4444;font-weight:600;'>9 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 21 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (21 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>5 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 2,
        "to": 0,
        "distance": 40,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 18,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 2 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 40 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>18 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        50,
        40,
        35,
        57,
        59
      ],
      [
        50,
        10000000,
        52,
        39,
        31,
        27
      ],
      [
        40,
        52,
        10000000,
        14,
        35,
        76
      ],
      [
        35,
        39,
        14,
        10000000,
        25,
        62
      ],
      [
        57,
        31,
        35,
        25,
        10000000,
        58
      ],
      [
        59,
        27,
        76,
        62,
        58,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID6_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID6_H_01",
    "numCustomers": 5,
    "instanceId": 6,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 36,
    "objectiveValue": 178.6,
    "totalDistance": 176,
    "handlingCost": 2.6,
    "tour": [
      0,
      1,
      3,
      4,
      5,
      2,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 36,
        "beta": 22,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 15,
        "beta": 3,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 4,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 7,
        "beta": 9,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 3,
        "beta": 8,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 7,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 1,
        "distance": 9,
        "deliverA": 15,
        "pickupB": 3,
        "aOnTruck": 36,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 15,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 1:</strong> El camión viaja una distancia de 9 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>15 unidades α</span> (entrega requerida). ⚠️ Se requirieron 15 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>3 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 1,
        "to": 3,
        "distance": 26,
        "deliverA": 7,
        "pickupB": 9,
        "aOnTruck": 21,
        "bOnTruck": 3,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 22,
        "handlingCost": 0.3,
        "explanation": "<strong>Paso 2 — Cliente 1 → Cliente 3:</strong> Recorrido de 26 km. Se entregan <span style='color:#ef4444;font-weight:600;'>7 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 22 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (22 operaciones × h=0.1 = 0.30 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>9 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 3,
        "to": 4,
        "distance": 48,
        "deliverA": 3,
        "pickupB": 8,
        "aOnTruck": 14,
        "bOnTruck": 12,
        "slots": [
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 36,
        "handlingCost": 2.3,
        "explanation": "<strong>Paso 3 — Cliente 3 → Cliente 4:</strong> Recorrido de 48 km. Se entregan <span style='color:#ef4444;font-weight:600;'>3 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 36 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (36 operaciones × h=0.1 = 2.30 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>8 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 4,
        "to": 5,
        "distance": 15,
        "deliverA": 7,
        "pickupB": 0,
        "aOnTruck": 11,
        "bOnTruck": 20,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 10,
        "handlingCost": 0,
        "explanation": "<strong>Paso 4 — Cliente 4 → Cliente 5:</strong> Recorrido de 15 km. Se entregan <span style='color:#ef4444;font-weight:600;'>7 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 10 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (10 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 5,
        "to": 2,
        "distance": 32,
        "deliverA": 4,
        "pickupB": 2,
        "aOnTruck": 4,
        "bOnTruck": 20,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 16,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 5 → Cliente 2:</strong> Recorrido de 32 km. Se entregan <span style='color:#ef4444;font-weight:600;'>4 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 16 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (16 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 2,
        "to": 0,
        "distance": 46,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 22,
        "slots": [
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 2 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 46 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>22 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        9,
        46,
        34,
        21,
        36
      ],
      [
        9,
        10000000,
        55,
        26,
        27,
        42
      ],
      [
        46,
        55,
        10000000,
        80,
        37,
        32
      ],
      [
        34,
        26,
        80,
        10000000,
        48,
        63
      ],
      [
        21,
        27,
        37,
        48,
        10000000,
        15
      ],
      [
        36,
        42,
        32,
        63,
        15,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID7_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID7_H_01",
    "numCustomers": 5,
    "instanceId": 7,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 32,
    "objectiveValue": 235.2,
    "totalDistance": 233,
    "handlingCost": 2.2,
    "tour": [
      0,
      5,
      2,
      1,
      4,
      3,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 32,
        "beta": 32,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 8,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 11,
        "beta": 7,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 6,
        "beta": 8,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 4,
        "beta": 15,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 3,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 5,
        "distance": 31,
        "deliverA": 3,
        "pickupB": 0,
        "aOnTruck": 32,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 3,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 5:</strong> El camión viaja una distancia de 31 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>3 unidades α</span> (entrega requerida). ⚠️ Se requirieron 3 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 5,
        "to": 2,
        "distance": 44,
        "deliverA": 11,
        "pickupB": 7,
        "aOnTruck": 29,
        "bOnTruck": 0,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 14,
        "handlingCost": 0,
        "explanation": "<strong>Paso 2 — Cliente 5 → Cliente 2:</strong> Recorrido de 44 km. Se entregan <span style='color:#ef4444;font-weight:600;'>11 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 14 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (14 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>7 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 2,
        "to": 1,
        "distance": 10,
        "deliverA": 8,
        "pickupB": 2,
        "aOnTruck": 18,
        "bOnTruck": 7,
        "slots": [
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "B",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 22,
        "handlingCost": 0.7,
        "explanation": "<strong>Paso 3 — Cliente 2 → Cliente 1:</strong> Recorrido de 10 km. Se entregan <span style='color:#ef4444;font-weight:600;'>8 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 22 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (22 operaciones × h=0.1 = 0.70 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 1,
        "to": 4,
        "distance": 40,
        "deliverA": 4,
        "pickupB": 15,
        "aOnTruck": 10,
        "bOnTruck": 9,
        "slots": [
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 32,
        "handlingCost": 1.5,
        "explanation": "<strong>Paso 4 — Cliente 1 → Cliente 4:</strong> Recorrido de 40 km. Se entregan <span style='color:#ef4444;font-weight:600;'>4 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 32 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (32 operaciones × h=0.1 = 1.50 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>15 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 4,
        "to": 3,
        "distance": 33,
        "deliverA": 6,
        "pickupB": 8,
        "aOnTruck": 6,
        "bOnTruck": 24,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "EMPTY",
          "A",
          "EMPTY",
          "A",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 8,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 4 → Cliente 3:</strong> Recorrido de 33 km. Se entregan <span style='color:#ef4444;font-weight:600;'>6 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 8 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (8 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>8 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 3,
        "to": 0,
        "distance": 75,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 32,
        "slots": [
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 3 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 75 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>32 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        74,
        68,
        75,
        68,
        31
      ],
      [
        74,
        10000000,
        10,
        72,
        40,
        52
      ],
      [
        68,
        10,
        10000000,
        77,
        45,
        44
      ],
      [
        75,
        72,
        77,
        10000000,
        33,
        83
      ],
      [
        68,
        40,
        45,
        33,
        10000000,
        64
      ],
      [
        31,
        52,
        44,
        83,
        64,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID8_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID8_H_01",
    "numCustomers": 5,
    "instanceId": 8,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 34,
    "objectiveValue": 191.6,
    "totalDistance": 191,
    "handlingCost": 0.6,
    "tour": [
      0,
      1,
      5,
      2,
      3,
      4,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 34,
        "beta": 16,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 2,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 6,
        "beta": 4,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 5,
        "beta": 7,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 2,
        "beta": 5,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 19,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 1,
        "distance": 20,
        "deliverA": 2,
        "pickupB": 0,
        "aOnTruck": 34,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 2,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 1:</strong> El camión viaja una distancia de 20 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>2 unidades α</span> (entrega requerida). ⚠️ Se requirieron 2 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 1,
        "to": 5,
        "distance": 18,
        "deliverA": 19,
        "pickupB": 0,
        "aOnTruck": 32,
        "bOnTruck": 0,
        "slots": [
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 21,
        "handlingCost": 0,
        "explanation": "<strong>Paso 2 — Cliente 1 → Cliente 5:</strong> Recorrido de 18 km. Se entregan <span style='color:#ef4444;font-weight:600;'>19 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 21 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (21 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 5,
        "to": 2,
        "distance": 61,
        "deliverA": 6,
        "pickupB": 4,
        "aOnTruck": 13,
        "bOnTruck": 0,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 27,
        "handlingCost": 0,
        "explanation": "<strong>Paso 3 — Cliente 5 → Cliente 2:</strong> Recorrido de 61 km. Se entregan <span style='color:#ef4444;font-weight:600;'>6 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 27 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (27 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>4 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 2,
        "to": 3,
        "distance": 4,
        "deliverA": 5,
        "pickupB": 7,
        "aOnTruck": 7,
        "bOnTruck": 4,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 34,
        "handlingCost": 0.6,
        "explanation": "<strong>Paso 4 — Cliente 2 → Cliente 3:</strong> Recorrido de 4 km. Se entregan <span style='color:#ef4444;font-weight:600;'>5 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 34 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (34 operaciones × h=0.1 = 0.60 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>7 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 3,
        "to": 4,
        "distance": 15,
        "deliverA": 2,
        "pickupB": 5,
        "aOnTruck": 2,
        "bOnTruck": 11,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY"
        ],
        "handlingCount": 7,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 3 → Cliente 4:</strong> Recorrido de 15 km. Se entregan <span style='color:#ef4444;font-weight:600;'>2 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 7 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (7 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>5 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 4,
        "to": 0,
        "distance": 73,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 16,
        "slots": [
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 4 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 73 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>16 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        20,
        75,
        71,
        73,
        33
      ],
      [
        20,
        10000000,
        75,
        72,
        78,
        18
      ],
      [
        75,
        75,
        10000000,
        4,
        17,
        61
      ],
      [
        71,
        72,
        4,
        10000000,
        15,
        59
      ],
      [
        73,
        78,
        17,
        15,
        10000000,
        67
      ],
      [
        33,
        18,
        61,
        59,
        67,
        10000000
      ]
    ]
  },
  "Solucion_5_Clientes_ID9_H_01.txt": {
    "instance": "Solucion_5_Clientes_ID9_H_01",
    "numCustomers": 5,
    "instanceId": 9,
    "h": 0.1,
    "h_a": 0.1,
    "h_b": 0.1,
    "capacity": 36,
    "objectiveValue": 277.3,
    "totalDistance": 276,
    "handlingCost": 1.3,
    "tour": [
      0,
      2,
      1,
      3,
      5,
      4,
      0
    ],
    "nodes": [
      {
        "id": 0,
        "alpha": 36,
        "beta": 20,
        "isDepot": true,
        "label": "Depósito"
      },
      {
        "id": 1,
        "alpha": 12,
        "beta": 2,
        "isDepot": false,
        "label": "Cliente 1"
      },
      {
        "id": 2,
        "alpha": 2,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 2"
      },
      {
        "id": 3,
        "alpha": 4,
        "beta": 6,
        "isDepot": false,
        "label": "Cliente 3"
      },
      {
        "id": 4,
        "alpha": 3,
        "beta": 12,
        "isDepot": false,
        "label": "Cliente 4"
      },
      {
        "id": 5,
        "alpha": 15,
        "beta": 0,
        "isDepot": false,
        "label": "Cliente 5"
      }
    ],
    "steps": [
      {
        "stepIndex": 0,
        "from": 0,
        "to": 2,
        "distance": 59,
        "deliverA": 2,
        "pickupB": 0,
        "aOnTruck": 36,
        "bOnTruck": 0,
        "slots": [
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 2,
        "handlingCost": 0,
        "explanation": "<strong>Paso 1 — Depósito (Nodo 0) → Cliente 2:</strong> El camión viaja una distancia de 59 km. Al llegar descarga <span style='color:#ef4444;font-weight:600;'>2 unidades α</span> (entrega requerida). ⚠️ Se requirieron 2 operaciones de manipulación (handling) con costo adicional de 0.00. Posteriormente recolecta <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> que se colocan al final del compartimiento LIFO."
      },
      {
        "stepIndex": 1,
        "from": 2,
        "to": 1,
        "distance": 26,
        "deliverA": 12,
        "pickupB": 2,
        "aOnTruck": 34,
        "bOnTruck": 0,
        "slots": [
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 14,
        "handlingCost": 0,
        "explanation": "<strong>Paso 2 — Cliente 2 → Cliente 1:</strong> Recorrido de 26 km. Se entregan <span style='color:#ef4444;font-weight:600;'>12 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 14 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (14 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>2 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 2,
        "from": 1,
        "to": 3,
        "distance": 63,
        "deliverA": 4,
        "pickupB": 6,
        "aOnTruck": 22,
        "bOnTruck": 2,
        "slots": [
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 18,
        "handlingCost": 0.2,
        "explanation": "<strong>Paso 3 — Cliente 1 → Cliente 3:</strong> Recorrido de 63 km. Se entregan <span style='color:#ef4444;font-weight:600;'>4 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 18 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (18 operaciones × h=0.1 = 0.20 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>6 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 3,
        "from": 3,
        "to": 5,
        "distance": 54,
        "deliverA": 15,
        "pickupB": 0,
        "aOnTruck": 18,
        "bOnTruck": 8,
        "slots": [
          "B",
          "B",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A",
          "A"
        ],
        "handlingCount": 36,
        "handlingCost": 1.1,
        "explanation": "<strong>Paso 4 — Cliente 3 → Cliente 5:</strong> Recorrido de 54 km. Se entregan <span style='color:#ef4444;font-weight:600;'>15 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 36 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (36 operaciones × h=0.1 = 1.10 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>0 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 4,
        "from": 5,
        "to": 4,
        "distance": 63,
        "deliverA": 3,
        "pickupB": 12,
        "aOnTruck": 3,
        "bOnTruck": 8,
        "slots": [
          "EMPTY",
          "A",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "A",
          "EMPTY",
          "A",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 23,
        "handlingCost": 0,
        "explanation": "<strong>Paso 5 — Cliente 5 → Cliente 4:</strong> Recorrido de 63 km. Se entregan <span style='color:#ef4444;font-weight:600;'>3 unidades α</span>. ⚠️ <strong>Conflicto LIFO (Handling):</strong> Las 23 unidades de tipo β recolectadas previamente bloqueaban el acceso a las unidades α en la puerta trasera. Tuvieron que descargarse temporalmente y recargarse (23 operaciones × h=0.1 = 0.00 costo de manejo). Luego se recogen <span style='color:#06b6d4;font-weight:600;'>12 unidades β</span> para el depósito."
      },
      {
        "stepIndex": 5,
        "from": 4,
        "to": 0,
        "distance": 11,
        "deliverA": 0,
        "pickupB": 0,
        "aOnTruck": 0,
        "bOnTruck": 20,
        "slots": [
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "EMPTY",
          "B",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "B",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "EMPTY",
          "B",
          "B",
          "B",
          "EMPTY",
          "B",
          "B",
          "B",
          "B"
        ],
        "handlingCount": 0,
        "handlingCost": 0,
        "explanation": "<strong>Paso 6 — Cliente 4 → Depósito (Nodo 0):</strong> El camión regresa al depósito recorriendo 11 km transportando la totalidad de la carga recolectada (<span style='color:#06b6d4;font-weight:600;'>20 unidades β</span>). <strong>¡Tour completado exitosamente!</strong>"
      }
    ],
    "distMatrix": [
      [
        10000000,
        85,
        59,
        93,
        11,
        74
      ],
      [
        85,
        10000000,
        26,
        63,
        82,
        98
      ],
      [
        59,
        26,
        10000000,
        61,
        56,
        81
      ],
      [
        93,
        63,
        61,
        10000000,
        84,
        54
      ],
      [
        11,
        82,
        56,
        84,
        10000000,
        63
      ],
      [
        74,
        98,
        81,
        54,
        63,
        10000000
      ]
    ]
  }
};
